/*************/
/* IMPORT(S) */
/*************/
import java_cup.runtime.*;
import ast.*;
import java.io.PrintWriter;

parser code 
{:
	public Lexer lexer;
	public PrintWriter writer;

	public Parser(Lexer lexer, PrintWriter writer)
	{
		super(lexer);
		this.lexer = lexer;
		this.writer = writer;
	}
	public void report_error(String message, Object info)
	{
		
	}
	public void syntax_error(Symbol curr_token){
		int err_line = curr_token.left +1;
		writer.print("ERROR(" +err_line+")");
		writer.flush();
		System.exit(0);
	}
:}

/************************/
/* CUSTOMIZE CUP PARSER */
/************************/
scan with
{:
	Symbol s;
	s = lexer.next_token();
	//System.out.print(s.sym);
	//Block for debug - delete later -----------------------------------------
	System.out.print("[");
	System.out.print(lexer.getLine());
	System.out.print(":");
	System.out.print(lexer.getTokenStartPosition());
	System.out.print("] ");
	System.out.print(TokenNames.terminalNames[s.sym]);
	if (s.value != null)
	{
		System.out.print("( ");
		System.out.print(s.value);
		System.out.print(" )");
	}
	System.out.print("\n");
	//-------------------------------------------------------------------------
	return s; 
:};

/*************/
/* TERMINALS */
/*************/
terminal IF;
terminal EQ;
terminal DOT;
terminal PLUS;
terminal MINUS;
terminal TIMES;
terminal WHILE;
terminal DIVIDE;
terminal LPAREN;
terminal RPAREN;
terminal LBRACK;
terminal RBRACK;
terminal LBRACE;
terminal RBRACE;
terminal SEMICOLON;
terminal COMMA;
terminal NIL;
terminal ASSIGN;
terminal LT;
terminal GT; 
terminal CLASS;
terminal NEW;
terminal EXTENDS;
terminal ARRAY;
terminal RETURNN;

/*************/
/* TERMINALS */
/*************/
terminal Integer INT;
terminal String ID;
terminal String STRING;
terminal TYPE_INT;
terminal TYPE_STRING;
terminal TYPE_VOID;

/*****************/
/* NON TERMINALS */
/*****************/
non terminal AstExp exp;
non terminal AstVar var;
non terminal AstStmt stmt;
non terminal AstStmtList stmtList;

non terminal AstProgram program;
non terminal AstDec dec;
non terminal AstDecList decList;
non terminal AstType type;
non terminal AstVarDec varDec;
non terminal AstFuncDec funcDec;
non terminal AstClassDec classDec;
non terminal AstArrayTypeDef arrayTypeDef;
non terminal AstNewExp newExp;
non terminal AstCallExp callExp;
non terminal AstClassField classField;
non terminal AstClassFieldList classFieldsList;
non terminal AstTypeNameList typeNameList;
non terminal AstExpList expList;

/***********************/
/* OPERATOR PRECEDENCE */
/***********************/
precedence nonassoc ASSIGN;
precedence left EQ; 
precedence left LT;
precedence left GT;

precedence left PLUS;
precedence left MINUS;
precedence left TIMES;
precedence left DIVIDE;

precedence left LBRACK; // Array
precedence left DOT;


/************************/
/* START WITH: stmtList */
/************************/
start with program;

/********************/
/* DERIVATION RULES */
/********************/

program		::=		decList:l		{: RESULT = new AstProgram(l, lleft); :}
					;

decList		::=		decList:l dec:d		{: l.add(d); RESULT=l; :}
					| dec:d 			{: RESULT = new AstDecList(d, dleft);	:}
					;

dec 		::= 	varDec:v			{: RESULT = v; :}
					| funcDec:f 		{: RESULT = f; :}
					| classDec:c 		{: RESULT = c; :}
					| arrayTypeDef:a	{: RESULT = a; :}
					;

type  		::= 	TYPE_INT:t			{: RESULT = new AstType("int", tleft); :}
					| TYPE_STRING:t		{: RESULT = new AstType("string", tleft); :}
					| TYPE_VOID:t		{: RESULT = new AstType("void", tleft); :}
					| ID:i 				{: RESULT = new AstType(i, ileft); :}
					;
			
// Declarations  ------------------------------------------------------------

varDec		::= 	type:t ID:i ASSIGN exp:e SEMICOLON	{: RESULT = new AstVarDec(t,i,e,tleft); :}
					| type:t ID:i ASSIGN newExp:e SEMICOLON	{: RESULT = new AstVarDec(t,i,e,tleft); :}
					| type:t ID:i SEMICOLON	{: RESULT = new AstVarDec(t, i, null, tleft); :}
					;

funcDec		::=		type:t ID:i LPAREN typeNameList:l RPAREN LBRACE stmtList:body RBRACE
					{: RESULT = new AstFuncDec(t,i,l,body,tleft); :}
					| type:t ID:i LPAREN RPAREN LBRACE stmtList:body RBRACE
					{: RESULT = new AstFuncDec(t,i,null,body, tleft); :}
					;

// part of the funcDec
typeNameList	::= 	type: t ID:i 		{: RESULT = new AstTypeNameList(t,i,tleft); :}
						| typeNameList:l COMMA type:t ID:i  {: l.add(t,i); RESULT = l; :}
						;

classDec	::= 	CLASS ID:i LBRACE classFieldsList:fields RBRACE		{: RESULT = new AstClassDec(i, null, fields, ileft);	:}
					| CLASS ID:i EXTENDS ID:sup LBRACE classFieldsList:fields RBRACE	{: RESULT = new AstClassDec(i, sup, fields, ileft);	:}
					;

classFieldsList ::= classField:f			{: RESULT = new AstClassFieldList(f, fleft); :}
					| classFieldsList:l classField:f  {: l.add(f); RESULT = l; :}
					;

classField	::= 	varDec:v 				{: RESULT = new AstClassField(v, vleft);	:}
					| funcDec:f 			{: RESULT = new AstClassField(f, fleft);	:}
					;

arrayTypeDef ::= 	ARRAY ID:i EQ type:t LBRACK RBRACK SEMICOLON {: RESULT = new AstArrayTypeDef(i,t, ileft); :}
					;

// Statements  ------------------------------------------------------------
stmtList	::=		stmtList:l	stmt:s		{: l.add(s); RESULT = l;    :}
					| stmt:s				{: RESULT = new AstStmtList(s,sleft); :}
					;

stmt		::=		varDec:v 													{: RESULT = new AstStmtDec(v, vleft); :}
					| var:v ASSIGN exp:e SEMICOLON								{: RESULT = new AstStmtAssign(v,e,vleft); :}
					| var:v ASSIGN newExp:e SEMICOLON							{: RESULT = new AstStmtAssignNew(v,e, vleft); :}
					| RETURNN exp:e SEMICOLON									{: RESULT = new AstStmtReturn(e, eleft); :}
					| IF    LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE	{: RESULT = new AstStmtIf(   cond,body,condleft); :}
					| WHILE LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE	{: RESULT = new AstStmtWhile(cond,body,condleft); :}
					| callExp:e	SEMICOLON										{: RESULT = new AstStmtCall(e, eleft); :}
					;

// Expressions  ------------------------------------------------------------
exp			::=		INT:i								{: RESULT = new AstExpInt(i, ileft);          :}
					| var:v								{: RESULT = new AstExpVar(v, vleft);          :}
					| LPAREN exp:e RPAREN				{: RESULT = e; :}
					| exp:e1 PLUS  exp:e2				{: RESULT = new AstExpBinop(e1, e2, 0, e1left);:}
					| exp:e1 MINUS exp:e2				{: RESULT = new AstExpBinop(e1, e2, 1,e1left);:}
					| exp:e1 TIMES exp:e2				{: RESULT = new AstExpBinop(e1, e2, 2,e1left);:}
					| exp:e1 DIVIDE exp:e2				{: RESULT = new AstExpBinop(e1, e2, 3,e1left);:}
					| exp:e1 LT exp:e2					{: RESULT = new AstExpBinop(e1, e2, 4,e1left);:}
					| exp:e1 GT exp:e2					{: RESULT = new AstExpBinop(e1, e2, 5,e1left);:}
					| exp:e1 EQ exp:e2					{: RESULT = new AstExpBinop(e1, e2, 6,e1left);:}
					| callExp:e 						{: RESULT = new AstExpCall(e, eleft);:}
					| MINUS INT:i						{: RESULT = new AstExpInt(-i, ileft);:}
					| NIL:n								{: RESULT = new AstExpNil(nleft);:}
					| STRING:s							{: RESULT = new AstExpString(s, sleft);:}
					;

newExp 		::= 	NEW type:t 							{: RESULT = new AstNewExp(t, null, tleft);	:}
					| NEW type:t LBRACK exp:e RBRACK	{: RESULT = new AstNewExp(t, e, tleft);	:}
					;

expList 	::= 	expList:l COMMA exp:e				{: l.add(e); RESULT=l;		:}
					| exp:e								{: RESULT = new AstExpList(e,eleft);	:}
					;

callExp		::= 	var:v DOT ID:i LPAREN expList:l RPAREN	{: RESULT = new AstCallExp(v,i,l, vleft);	:}
					| var:v DOT ID:i LPAREN RPAREN 		{: RESULT = new AstCallExp(v,i,null, vleft);	:}
					| ID:i LPAREN expList:l RPAREN		{: RESULT = new AstCallExp(null, i, l, ileft); 	:}
					| ID:i LPAREN RPAREN				{: RESULT = new AstCallExp(null, i, null, ileft);	:}
					;

var			::=		ID:name								{: RESULT = new AstVarSimple(name, nameleft);       :}
					| var:v DOT ID:fieldName			{: RESULT = new AstVarField(v,fieldName, vleft); :}
					| var:v LBRACK exp:e RBRACK			{: RESULT = new AstVarSubscript(v,e, vleft);     :}
					;
					